version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.13.1
    steps:
      - checkout
      - run:
          name: Install Node Modules
          command: npm install
      - run:
          name: Test
          command: npm test
      - store_test_results:
          path: reports
workflows:
  version: 2
  test:
    jobs:
      - test